services:
  - type: web
    name: line-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: LINE_CHANNEL_SECRET
        value: your_line_channel_secret
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: your_access_token
